// create separate namespace for all the Emscripten stuff.. otherwise naming clashes may occur especially when 
// optimizing using closure compiler..
window.spp_backend_state_V2M= {
	notReady: true,
	adapterCallback: function(){}	// overwritten later	
};
window.spp_backend_state_V2M["onRuntimeInitialized"] = function() {	// emscripten callback needed in case async init is used (e.g. for WASM)
	this.notReady= false;
	this.adapterCallback();
}.bind(window.spp_backend_state_V2M);

var backend_V2M = (function(Module) {var c;c||(c=typeof Module !== 'undefined' ? Module : {});var k={},l;for(l in c)c.hasOwnProperty(l)&&(k[l]=c[l]);c.arguments=[];c.thisProgram="./this.program";c.quit=function(a,b){throw b;};c.preRun=[];c.postRun=[];var m=!1,n=!1,p=!1,aa=!1;
if(c.ENVIRONMENT)if("WEB"===c.ENVIRONMENT)m=!0;else if("WORKER"===c.ENVIRONMENT)n=!0;else if("NODE"===c.ENVIRONMENT)p=!0;else if("SHELL"===c.ENVIRONMENT)aa=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else m="object"===typeof window,n="function"===typeof importScripts,p="object"===typeof process&&"function"===typeof require&&!m&&!n,aa=!m&&!p&&!n;
if(p){var ba,ca;c.read=function(a,b){ba||(ba=require("fs"));ca||(ca=require("path"));a=ca.normalize(a);a=ba.readFileSync(a);return b?a:a.toString()};c.readBinary=function(a){a=c.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(c.thisProgram=process.argv[1].replace(/\\/g,"/"));c.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=c);process.on("uncaughtException",function(a){if(!(a instanceof q))throw a;});process.on("unhandledRejection",
function(){c.printErr("node.js exiting due to unhandled promise rejection");process.exit(1)});c.inspect=function(){return"[Emscripten Module object]"}}else if(aa)"undefined"!=typeof read&&(c.read=function(a){return read(a)}),c.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?c.arguments=scriptArgs:"undefined"!=typeof arguments&&(c.arguments=arguments),"function"===typeof quit&&
(c.quit=function(a){quit(a)});else if(m||n)c.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},n&&(c.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),c.readAsync=function(a,b,d){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?b(e.response):d()};e.onerror=d;e.send(null)},"undefined"!=
typeof arguments&&(c.arguments=arguments),c.setWindowTitle=function(a){document.title=a};else throw Error("unknown runtime environment");c.print="undefined"!==typeof console?console.log:"undefined"!==typeof print?print:null;c.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn||c.print;c.print=c.print;c.printErr=c.printErr;for(l in k)k.hasOwnProperty(l)&&(c[l]=k[l]);k=void 0;da=ea=ha=ia=function(){r("cannot use the stack before compiled code is ready to run, and has provided stack access")};
function ja(a){assert(!ka);var b=u;u=u+a+15&-16;return b}function la(a){var b;b||(b=16);return Math.ceil(a/b)*b}function ma(a){na||(na={});na[a]||(na[a]=1,c.printErr(a))}var na,oa=0;function assert(a,b){a||r("Assertion failed: "+b)}
var ra={stackSave:function(){da()},stackRestore:function(){ea()},arrayToC:function(a){var b=ha(a.length);assert(0<=a.length,"writeArrayToMemory array must have a length (should be an array or typed array)");pa.set(a,b);return b},stringToC:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var d=(a.length<<2)+1,e=b=ha(d);assert("number"==typeof d,"stringToUTF8(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");qa(a,x,e,d)}return b}},sa={string:ra.stringToC,
array:ra.arrayToC};function ta(a,b){if(0===b||!a)return"";for(var d=0,e,f=0;;){assert(a+f<y);e=x[a+f>>0];d|=e;if(0==e&&!b)break;f++;if(b&&f==b)break}b||(b=f);e="";if(128>d){for(;0<b;)d=String.fromCharCode.apply(String,x.subarray(a,a+Math.min(b,1024))),e=e?e+d:d,a+=1024,b-=1024;return e}return ua(x,a)}var va="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ua(a,b){for(var d=b;a[d];)++d;if(16<d-b&&a.subarray&&va)return va.decode(a.subarray(b,d));for(d="";;){var e=a[b++];if(!e)return d;if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;if(224==(e&240))e=(e&15)<<12|f<<6|g;else{var h=a[b++]&63;if(240==(e&248))e=(e&7)<<18|f<<12|g<<6|h;else{var t=a[b++]&63;if(248==(e&252))e=(e&3)<<24|f<<18|g<<12|h<<6|t;else{var w=a[b++]&63;e=(e&1)<<30|f<<24|g<<18|h<<12|t<<6|w}}}65536>e?d+=String.fromCharCode(e):(e-=
65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}}
function qa(a,b,d,e){if(!(0<e))return 0;var f=d;e=d+e-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);55296<=h&&57343>=h&&(h=65536+((h&1023)<<10)|a.charCodeAt(++g)&1023);if(127>=h){if(d>=e)break;b[d++]=h}else{if(2047>=h){if(d+1>=e)break;b[d++]=192|h>>6}else{if(65535>=h){if(d+2>=e)break;b[d++]=224|h>>12}else{if(2097151>=h){if(d+3>=e)break;b[d++]=240|h>>18}else{if(67108863>=h){if(d+4>=e)break;b[d++]=248|h>>24}else{if(d+5>=e)break;b[d++]=252|h>>30;b[d++]=128|h>>24&63}b[d++]=128|h>>18&63}b[d++]=128|
h>>12&63}b[d++]=128|h>>6&63}b[d++]=128|h&63}}b[d]=0;return d-f}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function xa(a){return a.replace(/__Z[\w\d_]+/g,function(a){ma("warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling");return a===a?a:a+" ["+a+"]"})}
function ya(){a:{var a=Error();if(!a.stack){try{throw Error(0);}catch(b){a=b}if(!a.stack){a="(no stack trace available)";break a}}a=a.stack.toString()}c.extraStackTrace&&(a+="\n"+c.extraStackTrace());return xa(a)}var buffer,pa,x,za,z,A;
function Aa(){c.HEAP8=pa=new Int8Array(buffer);c.HEAP16=za=new Int16Array(buffer);c.HEAP32=z=new Int32Array(buffer);c.HEAPU8=x=new Uint8Array(buffer);c.HEAPU16=new Uint16Array(buffer);c.HEAPU32=A=new Uint32Array(buffer);c.HEAPF32=new Float32Array(buffer);c.HEAPF64=new Float64Array(buffer)}var Ba,u,ka,Ca,Da,B,Ea,C;Ba=u=Ca=Da=B=Ea=C=0;ka=!1;
function Fa(){34821223==A[(B>>2)-1]&&2310721022==A[(B>>2)-2]||r("Stack overflow! Stack cookie has been overwritten, expected hex dwords 0x89BACDFE and 0x02135467, but received 0x"+A[(B>>2)-2].toString(16)+" "+A[(B>>2)-1].toString(16));if(1668509029!==z[0])throw"Runtime error: The application has corrupted its heap memory area (address zero)!";}
function Ga(){r("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+y+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var Ha=c.TOTAL_STACK||5242880,y=c.TOTAL_MEMORY||67108864;y<Ha&&c.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+y+"! (TOTAL_STACK="+Ha+")");
assert("undefined"!==typeof Int32Array&&"undefined"!==typeof Float64Array&&void 0!==Int32Array.prototype.subarray&&void 0!==Int32Array.prototype.set,"JS engine does not provide full typed array support");
c.buffer?(buffer=c.buffer,assert(buffer.byteLength===y,"provided buffer should be "+y+" bytes, but it is "+buffer.byteLength)):("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(assert(0===y%65536),c.wasmMemory=new WebAssembly.Memory({initial:y/65536,maximum:y/65536}),buffer=c.wasmMemory.buffer):buffer=new ArrayBuffer(y),assert(buffer.byteLength===y),c.buffer=buffer);Aa();z[0]=1668509029;za[1]=25459;
if(115!==x[2]||99!==x[3])throw"Runtime error: expected the system to be little-endian!";function Ia(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var d=b.Vc;"number"===typeof d?void 0===b.V?c.dynCall_v(d):c.dynCall_vi(d,b.V):d(void 0===b.V?null:b.V)}}}var Ja=[],Ka=[],La=[],Ma=[],Na=[],D=!1,E=!1;function Oa(){var a=c.preRun.shift();Ja.unshift(a)}assert(Math.imul&&Math.fround&&Math.clz32&&Math.trunc,"this is a legacy browser, build with LEGACY_VM_SUPPORT");
var F=0,G=null,Pa=null,H={};function Qa(a){for(var b=a;H[a];)a=b+Math.random();return a}function Ra(a){F++;c.monitorRunDependencies&&c.monitorRunDependencies(F);a?(assert(!H[a]),H[a]=1,null===G&&"undefined"!==typeof setInterval&&(G=setInterval(function(){if(oa)clearInterval(G),G=null;else{var a=!1,d;for(d in H)a||(a=!0,c.printErr("still waiting on run dependencies:")),c.printErr("dependency: "+d);a&&c.printErr("(end of list)")}},1E4))):c.printErr("warning: run dependency added without ID")}
function Sa(a){F--;c.monitorRunDependencies&&c.monitorRunDependencies(F);a?(assert(H[a]),delete H[a]):c.printErr("warning: run dependency removed without ID");0==F&&(null!==G&&(clearInterval(G),G=null),Pa&&(a=Pa,Pa=null,a()))}c.preloadedImages={};c.preloadedAudios={};function Ta(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(c.wasmBinary)return new Uint8Array(c.wasmBinary);if(c.readBinary)return c.readBinary(f);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(v){r(v)}}function b(){return c.wasmBinary||!m&&!n||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function d(a){function d(a){t=a.exports;if(t.memory){a=t.memory;var b=c.buffer;a.byteLength<b.byteLength&&c.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);c.buffer=buffer=a;Aa()}c.asm=t;c.usingWasm=!0;Sa("wasm-instantiate")}function e(a){assert(c===v,"the Module object should not be replaced during async compilation - perhaps the order of HTML elements is wrong?");
v=null;d(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a).catch(function(a){c.printErr("failed to asynchronously prepare wasm: "+a);r(a)})}if("object"!==typeof WebAssembly)return c.printErr("no native wasm support detected"),!1;if(!(c.wasmMemory instanceof WebAssembly.Memory))return c.printErr("no native wasm Memory in use"),!1;a.memory=c.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;Ra("wasm-instantiate");if(c.instantiateWasm)try{return c.instantiateWasm(h,
d)}catch(fa){return c.printErr("Module.instantiateWasm callback failed with error: "+fa),!1}var v=c;c.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Ta(f)||"function"!==typeof fetch?g(e):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),h).then(e).catch(function(a){c.printErr("wasm streaming compile failed: "+a);c.printErr("falling back to ArrayBuffer instantiation");g(e)});return{}}var e="v2m.wast",f="v2m.wasm",g="v2m.temp.asm.js";"function"===typeof c.locateFile&&
(Ta(e)||(e=c.locateFile(e)),Ta(f)||(f=c.locateFile(f)),Ta(g)||(g=c.locateFile(g)));var h={global:null,env:null,asm2wasm:{"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},parent:c},t=null;c.asmPreload=c.asm;var w=c.reallocBuffer;c.reallocBuffer=function(a){if("asmjs"===M)var b=w(a);else a:{var d=c.usingWasm?65536:16777216;0<a%d&&(a+=d-a%d);d=c.buffer.byteLength;if(c.usingWasm)try{b=-1!==c.wasmMemory.grow((a-d)/65536)?c.buffer=c.wasmMemory.buffer:null;break a}catch(Tb){console.error("Module.reallocBuffer: Attempted to grow from "+
d+" bytes to "+a+" bytes, but got error: "+Tb);b=null;break a}b=void 0}return b};var M="";c.asm=function(a,b){if(!b.table){a=c.wasmTableSize;void 0===a&&(a=1024);var e=c.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:a,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);c.wasmTable=b.table}b.memoryBase||(b.memoryBase=c.STATIC_BASE);b.tableBase||(b.tableBase=0);(b=d(b))||
r("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");return b}})();Ba=1024;u=Ba+3208592;Ka.push();c.STATIC_BASE=Ba;c.STATIC_BUMP=3208592;var Ua=u;u+=16;assert(0==Ua%8);function ___cxa_free_exception(a){try{return Wa(a)}catch(b){c.printErr("exception during cxa_free_exception: "+b)}}function Xa(){return!!Xa.W}var Ya=0,Za={};
function $a(){var a=Ya;if(!a)return(ia(0),0)|0;var b=Za[a],d=b.type;if(!d)return(ia(0),a)|0;var e=Array.prototype.slice.call(arguments);c.___cxa_is_pointer_type(d);ab||(ab=bb(4));z[ab>>2]=a;a=ab;for(var f=0;f<e.length;f++)if(e[f]&&c.___cxa_can_catch(e[f],d,a))return a=z[a>>2],b.Aa=a,(ia(e[f]),a)|0;a=z[a>>2];return(ia(d),a)|0}
var ab,I={C:1,s:2,Ec:3,Ab:4,v:5,ga:6,Ta:7,Yb:8,P:9,hb:10,ba:11,Oc:11,wa:12,O:13,tb:14,kc:15,R:16,da:17,Pc:18,T:19,ea:20,L:21,l:22,Tb:23,va:24,B:25,Lc:26,ub:27,fc:28,U:29,Bc:30,Mb:31,uc:32,qb:33,yc:34,bc:42,xb:43,ib:44,Db:45,Eb:46,Fb:47,Lb:48,Mc:49,Wb:50,Cb:51,nb:35,Zb:37,Za:52,bb:53,Qc:54,Ub:55,cb:56,eb:57,ob:35,fb:59,ic:60,Xb:61,Ic:62,hc:63,cc:64,dc:65,Ac:66,$b:67,Wa:68,Fc:69,jb:70,vc:71,Ob:72,rb:73,ab:74,pc:76,$a:77,zc:78,Gb:79,Hb:80,Kb:81,Jb:82,Ib:83,jc:38,fa:39,Pb:36,S:40,qc:95,tc:96,mb:104,Vb:105,
Xa:97,xc:91,nc:88,ec:92,Cc:108,lb:111,Ua:98,kb:103,Sb:101,Qb:100,Jc:110,vb:112,wb:113,zb:115,Ya:114,pb:89,Nb:90,wc:93,Dc:94,Va:99,Rb:102,Bb:106,lc:107,Kc:109,Nc:87,sb:122,Gc:116,oc:95,ac:123,yb:84,rc:75,gb:125,mc:131,sc:130,Hc:86},cb={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",
13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",
35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",
54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",
75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",
92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",
109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function db(a){c.___errno_location?z[c.___errno_location()>>2]=a:c.printErr("failed to set errno from JS");return a}
function eb(a,b){for(var d=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),d++):d&&(a.splice(e,1),d--)}if(b)for(;d;d--)a.unshift("..");return a}function fb(a){var b="/"===a.charAt(0),d="/"===a.substr(-1);(a=eb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&d&&(a+="/");return(b?"/":"")+a}
function gb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function hb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function ib(){var a=Array.prototype.slice.call(arguments,0);return fb(a.join("/"))}function J(a,b){return fb(a+"/"+b)}
function jb(){for(var a="",b=!1,d=arguments.length-1;-1<=d&&!b;d--){b=0<=d?arguments[d]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=eb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var kb=[];function lb(a,b){kb[a]={input:[],output:[],G:b};mb(a,nb)}
var nb={open:function(a){var b=kb[a.node.rdev];if(!b)throw new K(I.T);a.tty=b;a.seekable=!1},close:function(a){a.tty.G.flush(a.tty)},flush:function(a){a.tty.G.flush(a.tty)},read:function(a,b,d,e){if(!a.tty||!a.tty.G.pa)throw new K(I.ga);for(var f=0,g=0;g<e;g++){try{var h=a.tty.G.pa(a.tty)}catch(t){throw new K(I.v);}if(void 0===h&&0===f)throw new K(I.ba);if(null===h||void 0===h)break;f++;b[d+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,d,e){if(!a.tty||!a.tty.G.$)throw new K(I.ga);
for(var f=0;f<e;f++)try{a.tty.G.$(a.tty,b[d+f])}catch(g){throw new K(I.v);}e&&(a.node.timestamp=Date.now());return f}},pb={pa:function(a){if(!a.input.length){var b=null;if(p){var d=new Buffer(256),e=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(h){}}try{e=fs.readSync(f,d,0,256,null)}catch(h){if(-1!=h.toString().indexOf("EOF"))e=0;else throw h;}g&&fs.closeSync(f);0<e?b=d.slice(0,e).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ob(b)}return a.input.shift()},$:function(a,b){null===b||10===b?(c.print(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(c.print(ua(a.output,0)),a.output=[])}},qb={$:function(a,b){null===b||10===b?(c.printErr(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&
0<a.output.length&&(c.printErr(ua(a.output,0)),a.output=[])}},L={m:null,i:function(){return L.createNode(null,"/",16895,0)},createNode:function(a,b,d,e){if(24576===(d&61440)||4096===(d&61440))throw new K(I.C);L.m||(L.m={dir:{node:{o:L.c.o,h:L.c.h,lookup:L.c.lookup,I:L.c.I,rename:L.c.rename,unlink:L.c.unlink,rmdir:L.c.rmdir,readdir:L.c.readdir,symlink:L.c.symlink},stream:{u:L.f.u}},file:{node:{o:L.c.o,h:L.c.h},stream:{u:L.f.u,read:L.f.read,write:L.f.write,ha:L.f.ha,sa:L.f.sa,ua:L.f.ua}},link:{node:{o:L.c.o,
h:L.c.h,readlink:L.c.readlink},stream:{}},ka:{node:{o:L.c.o,h:L.c.h},stream:rb}});d=sb(a,b,d,e);N(d.mode)?(d.c=L.m.dir.node,d.f=L.m.dir.stream,d.b={}):32768===(d.mode&61440)?(d.c=L.m.file.node,d.f=L.m.file.stream,d.g=0,d.b=null):40960===(d.mode&61440)?(d.c=L.m.link.node,d.f=L.m.link.stream):8192===(d.mode&61440)&&(d.c=L.m.ka.node,d.f=L.m.ka.stream);d.timestamp=Date.now();a&&(a.b[b]=d);return d},Ea:function(a){if(a.b&&a.b.subarray){for(var b=[],d=0;d<a.g;++d)b.push(a.b[d]);return b}return a.b},Wc:function(a){return a.b?
a.b.subarray?a.b.subarray(0,a.g):new Uint8Array(a.b):new Uint8Array},la:function(a,b){a.b&&a.b.subarray&&b>a.b.length&&(a.b=L.Ea(a),a.g=a.b.length);if(!a.b||a.b.subarray){var d=a.b?a.b.length:0;d>=b||(b=Math.max(b,d*(1048576>d?2:1.125)|0),0!=d&&(b=Math.max(b,256)),d=a.b,a.b=new Uint8Array(b),0<a.g&&a.b.set(d.subarray(0,a.g),0))}else for(!a.b&&0<b&&(a.b=[]);a.b.length<b;)a.b.push(0)},Oa:function(a,b){if(a.g!=b)if(0==b)a.b=null,a.g=0;else{if(!a.b||a.b.subarray){var d=a.b;a.b=new Uint8Array(new ArrayBuffer(b));
d&&a.b.set(d.subarray(0,Math.min(b,a.g)))}else if(a.b||(a.b=[]),a.b.length>b)a.b.length=b;else for(;a.b.length<b;)a.b.push(0);a.g=b}},c:{o:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;N(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.g:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.A=4096;b.blocks=Math.ceil(b.size/b.A);return b},
h:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&L.Oa(a,b.size)},lookup:function(){throw tb[I.s];},I:function(a,b,d,e){return L.createNode(a,b,d,e)},rename:function(a,b,d){if(N(a.mode)){try{var e=O(b,d)}catch(g){}if(e)for(var f in e.b)throw new K(I.fa);}delete a.parent.b[a.name];a.name=d;b.b[d]=a;a.parent=b},unlink:function(a,b){delete a.b[b]},rmdir:function(a,b){var d=O(a,b),e;for(e in d.b)throw new K(I.fa);delete a.b[b]},readdir:function(a){var b=
[".",".."],d;for(d in a.b)a.b.hasOwnProperty(d)&&b.push(d);return b},symlink:function(a,b,d){a=L.createNode(a,b,41471,0);a.link=d;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new K(I.l);return a.link}},f:{read:function(a,b,d,e,f){var g=a.node.b;if(f>=a.node.g)return 0;a=Math.min(a.node.g-f,e);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),d);else for(e=0;e<a;e++)b[d+e]=g[f+e];return a},write:function(a,b,d,e,f,g){if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.b||a.b.subarray)){if(g)return assert(0===f,"canOwn must imply no weird position inside the file"),a.b=b.subarray(d,d+e),a.g=e;if(0===a.g&&0===f)return a.b=new Uint8Array(b.subarray(d,d+e)),a.g=e;if(f+e<=a.g)return a.b.set(b.subarray(d,d+e),f),e}L.la(a,f+e);if(a.b.subarray&&b.subarray)a.b.set(b.subarray(d,d+e),f);else for(g=0;g<e;g++)a.b[f+g]=b[d+g];a.g=Math.max(a.g,f+e);return e},u:function(a,b,d){1===d?b+=a.position:2===d&&32768===(a.node.mode&61440)&&(b+=a.node.g);if(0>b)throw new K(I.l);return b},
ha:function(a,b,d){L.la(a.node,b+d);a.node.g=Math.max(a.node.g,b+d)},sa:function(a,b,d,e,f,g,h){if(32768!==(a.node.mode&61440))throw new K(I.T);d=a.node.b;if(h&2||d.buffer!==b&&d.buffer!==b.buffer){if(0<f||f+e<a.node.g)d.subarray?d=d.subarray(f,f+e):d=Array.prototype.slice.call(d,f,f+e);a=!0;e=bb(e);if(!e)throw new K(I.wa);b.set(d,e)}else a=!1,e=d.byteOffset;return{Na:e,Rc:a}},ua:function(a,b,d,e,f){if(32768!==(a.node.mode&61440))throw new K(I.T);if(f&2)return 0;L.f.write(a,b,0,e,d,!1);return 0}}},
P={N:!1,Ra:function(){P.N=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);P.ma={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},ia:function(a){return Buffer.W?Buffer.from(a):new Buffer(a)},i:function(a){assert(p);return P.createNode(null,"/",P.oa(a.Z.root),0)},createNode:function(a,b,d){if(!N(d)&&32768!==(d&61440)&&40960!==(d&61440))throw new K(I.l);a=sb(a,b,d);a.c=P.c;a.f=P.f;return a},oa:function(a){try{var b=
fs.lstatSync(a);P.N&&(b.mode=b.mode|(b.mode&292)>>2)}catch(d){if(!d.code)throw d;throw new K(I[d.code]);}return b.mode},j:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.i.Z.root);b.reverse();return ib.apply(null,b)},Da:function(a){a&=-2656257;var b=0,d;for(d in P.ma)a&d&&(b|=P.ma[d],a^=d);if(a)throw new K(I.l);return b},c:{o:function(a){a=P.j(a);try{var b=fs.lstatSync(a)}catch(d){if(!d.code)throw d;throw new K(I[d.code]);}P.N&&!b.A&&(b.A=4096);P.N&&!b.blocks&&(b.blocks=
(b.size+b.A-1)/b.A|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,A:b.A,blocks:b.blocks}},h:function(a,b){var d=P.j(a);try{void 0!==b.mode&&(fs.chmodSync(d,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(d,b.size)}catch(e){if(!e.code)throw e;throw new K(I[e.code]);}},lookup:function(a,b){var d=J(P.j(a),b);d=P.oa(d);return P.createNode(a,b,d)},I:function(a,b,d,e){a=P.createNode(a,b,d,e);b=P.j(a);
try{N(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new K(I[f.code]);}return a},rename:function(a,b,d){a=P.j(a);b=J(P.j(b),d);try{fs.renameSync(a,b)}catch(e){if(!e.code)throw e;throw new K(I[e.code]);}},unlink:function(a,b){a=J(P.j(a),b);try{fs.unlinkSync(a)}catch(d){if(!d.code)throw d;throw new K(I[d.code]);}},rmdir:function(a,b){a=J(P.j(a),b);try{fs.rmdirSync(a)}catch(d){if(!d.code)throw d;throw new K(I[d.code]);}},readdir:function(a){a=P.j(a);
try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new K(I[b.code]);}},symlink:function(a,b,d){a=J(P.j(a),b);try{fs.symlinkSync(d,a)}catch(e){if(!e.code)throw e;throw new K(I[e.code]);}},readlink:function(a){var b=P.j(a);try{return b=fs.readlinkSync(b),b=ub.relative(ub.resolve(a.i.Z.root),b)}catch(d){if(!d.code)throw d;throw new K(I[d.code]);}}},f:{open:function(a){var b=P.j(a.node);try{32768===(a.node.mode&61440)&&(a.K=fs.openSync(b,P.Da(a.flags)))}catch(d){if(!d.code)throw d;throw new K(I[d.code]);
}},close:function(a){try{32768===(a.node.mode&61440)&&a.K&&fs.closeSync(a.K)}catch(b){if(!b.code)throw b;throw new K(I[b.code]);}},read:function(a,b,d,e,f){if(0===e)return 0;try{return fs.readSync(a.K,P.ia(b.buffer),d,e,f)}catch(g){throw new K(I[g.code]);}},write:function(a,b,d,e,f){try{return fs.writeSync(a.K,P.ia(b.buffer),d,e,f)}catch(g){throw new K(I[g.code]);}},u:function(a,b,d){if(1===d)b+=a.position;else if(2===d&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.K).size}catch(e){throw new K(I[e.code]);
}if(0>b)throw new K(I.l);return b}}};u+=16;u+=16;u+=16;var vb=null,wb={},Q=[],xb=1,R=null,yb=!0,S={},K=null,tb={};
function T(a,b){a=jb("/",a);b=b||{};if(!a)return{path:"",node:null};var d={na:!0,aa:0},e;for(e in d)void 0===b[e]&&(b[e]=d[e]);if(8<b.aa)throw new K(I.S);a=eb(a.split("/").filter(function(a){return!!a}),!1);var f=vb;d="/";for(e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;f=O(f,a[e]);d=J(d,a[e]);f.J&&(!g||g&&b.na)&&(f=f.J.root);if(!g||b.H)for(g=0;40960===(f.mode&61440);)if(f=zb(d),d=jb(gb(d),f),f=T(d,{aa:b.aa}).node,40<g++)throw new K(I.S);}return{path:d,node:f}}
function U(a){for(var b;;){if(a===a.parent)return a=a.i.ta,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ab(a,b){for(var d=0,e=0;e<b.length;e++)d=(d<<5)-d+b.charCodeAt(e)|0;return(a+d>>>0)%R.length}function Bb(a){var b=Ab(a.parent.id,a.name);a.F=R[b];R[b]=a}function O(a,b){var d;if(d=(d=Cb(a,"x"))?d:a.c.lookup?0:I.O)throw new K(d,a);for(d=R[Ab(a.id,b)];d;d=d.F){var e=d.name;if(d.parent.id===a.id&&e===b)return d}return a.c.lookup(a,b)}
function sb(a,b,d,e){Db||(Db=function(a,b,d,e){a||(a=this);this.parent=a;this.i=a.i;this.J=null;this.id=xb++;this.name=b;this.mode=d;this.c={};this.f={};this.rdev=e},Db.prototype={},Object.defineProperties(Db.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Ha:{get:function(){return N(this.mode)}},Ga:{get:function(){return 8192===(this.mode&
61440)}}}));a=new Db(a,b,d,e);Bb(a);return a}function N(a){return 16384===(a&61440)}var Eb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Fb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Cb(a,b){if(yb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return I.O}else return I.O;return 0}
function Gb(a,b){try{return O(a,b),I.da}catch(d){}return Cb(a,"wx")}function Hb(){var a=4096;for(var b=0;b<=a;b++)if(!Q[b])return b;throw new K(I.va);}function Ib(a){Jb||(Jb=function(){},Jb.prototype={},Object.defineProperties(Jb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var b=new Jb,d;for(d in a)b[d]=a[d];a=b;b=Hb();a.fd=b;return Q[b]=a}var rb={open:function(a){a.f=wb[a.node.rdev].f;a.f.open&&a.f.open(a)},u:function(){throw new K(I.U);}};
function mb(a,b){wb[a]={f:b}}function Kb(a,b){var d="/"===b,e=!b;if(d&&vb)throw new K(I.R);if(!d&&!e){var f=T(b,{na:!1});b=f.path;f=f.node;if(f.J)throw new K(I.R);if(!N(f.mode))throw new K(I.ea);}b={type:a,Z:{},ta:b,Ja:[]};a=a.i(b);a.i=b;b.root=a;d?vb=a:f&&(f.J=b,f.i&&f.i.Ja.push(b))}function Lb(a,b,d){var e=T(a,{parent:!0}).node;a=hb(a);if(!a||"."===a||".."===a)throw new K(I.l);var f=Gb(e,a);if(f)throw new K(f);if(!e.c.I)throw new K(I.C);return e.c.I(e,a,b,d)}
function V(a,b){return Lb(a,(void 0!==b?b:511)&1023|16384,0)}function Mb(a,b,d){"undefined"===typeof d&&(d=b,b=438);return Lb(a,b|8192,d)}function Nb(a,b){if(!jb(a))throw new K(I.s);var d=T(b,{parent:!0}).node;if(!d)throw new K(I.s);b=hb(b);var e=Gb(d,b);if(e)throw new K(e);if(!d.c.symlink)throw new K(I.C);return d.c.symlink(d,b,a)}
function Ob(a){var b=T(a,{parent:!0}).node,d=hb(a),e=O(b,d);a:{try{var f=O(b,d)}catch(h){f=h.D;break a}var g=Cb(b,"wx");f=g?g:N(f.mode)?I.L:0}if(f)throw new K(f);if(!b.c.unlink)throw new K(I.C);if(e.J)throw new K(I.R);try{S.willDeletePath&&S.willDeletePath(a)}catch(h){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.c.unlink(b,d);b=Ab(e.parent.id,e.name);if(R[b]===e)R[b]=e.F;else for(b=R[b];b;){if(b.F===e){b.F=e.F;break}b=b.F}try{if(S.onDeletePath)S.onDeletePath(a)}catch(h){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function zb(a){a=T(a).node;if(!a)throw new K(I.s);if(!a.c.readlink)throw new K(I.l);return jb(U(a.parent),a.c.readlink(a))}function Pb(a,b){var d;"string"===typeof a?d=T(a,{H:!0}).node:d=a;if(!d.c.h)throw new K(I.C);d.c.h(d,{mode:b&4095|d.mode&-4096,timestamp:Date.now()})}
function Qb(a,b){if(""===a)throw new K(I.s);if("string"===typeof b){var d=Eb[b];if("undefined"===typeof d)throw Error("Unknown file open mode: "+b);b=d}var e=b&64?("undefined"===typeof e?438:e)&4095|32768:0;if("object"===typeof a)var f=a;else{a=fb(a);try{f=T(a,{H:!(b&131072)}).node}catch(h){}}d=!1;if(b&64)if(f){if(b&128)throw new K(I.da);}else f=Lb(a,e,0),d=!0;if(!f)throw new K(I.s);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!N(f.mode))throw new K(I.ea);if(!d&&(e=f?40960===(f.mode&61440)?I.S:N(f.mode)&&
("r"!==Fb(b)||b&512)?I.L:Cb(f,Fb(b)):I.s))throw new K(e);if(b&512){e=f;var g;"string"===typeof e?g=T(e,{H:!0}).node:g=e;if(!g.c.h)throw new K(I.C);if(N(g.mode))throw new K(I.L);if(32768!==(g.mode&61440))throw new K(I.l);if(e=Cb(g,"w"))throw new K(e);g.c.h(g,{size:0,timestamp:Date.now()})}b&=-641;f=Ib({node:f,path:U(f),flags:b,seekable:!0,position:0,f:f.f,Sa:[],error:!1});f.f.open&&f.f.open(f);!c.logReadFiles||b&1||(Rb||(Rb={}),a in Rb||(Rb[a]=1,c.printErr("read file: "+a)));try{S.onOpenFile&&(g=0,
1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),S.onOpenFile(a,g))}catch(h){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}return f}function Sb(a){a.X&&(a.X=null);try{a.f.close&&a.f.close(a)}catch(b){throw b;}finally{Q[a.fd]=null}}function Ub(a,b,d){if(!a.seekable||!a.f.u)throw new K(I.U);a.position=a.f.u(a,b,d);a.Sa=[];return a.position}
function Vb(a,b,d,e,f,g){if(0>e||0>f)throw new K(I.l);if(0===(a.flags&2097155))throw new K(I.P);if(N(a.node.mode))throw new K(I.L);if(!a.f.write)throw new K(I.l);a.flags&1024&&(f=Ub(a,0,2));var h=!0;if("undefined"===typeof f)f=a.position,h=!1;else if(!a.seekable)throw new K(I.U);b=a.f.write(a,b,d,e,f,g);h||(a.position+=b);try{if(a.path&&S.onWriteToFile)S.onWriteToFile(a.path)}catch(t){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+t.message)}return b}
function Wb(){K||(K=function(a,b){this.node=b;this.Qa=function(a){this.D=a;for(var b in I)if(I[b]===a){this.code=b;break}};this.Qa(a);this.message=cb[a];this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0});this.stack&&(this.stack=xa(this.stack))},K.prototype=Error(),K.prototype.constructor=K,[I.s].forEach(function(a){tb[a]=new K(a);tb[a].stack="<generic error, no stack>"}))}var Xb;function Yb(a,b){var d=0;a&&(d|=365);b&&(d|=146);return d}
function Zb(a,b,d,e){a=J("string"===typeof a?a:U(a),b);return V(a,Yb(d,e))}function $b(a,b){a="string"===typeof a?a:U(a);for(b=b.split("/").reverse();b.length;){var d=b.pop();if(d){var e=J(a,d);try{V(e)}catch(f){}a=e}}return e}function ac(a,b,d,e){a=J("string"===typeof a?a:U(a),b);d=Yb(d,e);return Lb(a,(void 0!==d?d:438)&4095|32768,0)}
function bc(a,b,d,e,f,g){a=b?J("string"===typeof a?a:U(a),b):a;e=Yb(e,f);f=Lb(a,(void 0!==e?e:438)&4095|32768,0);if(d){if("string"===typeof d){a=Array(d.length);b=0;for(var h=d.length;b<h;++b)a[b]=d.charCodeAt(b);d=a}Pb(f,e|146);a=Qb(f,"w");Vb(a,d,0,d.length,0,g);Sb(a);Pb(f,e)}return f}
function W(a,b,d,e){a=J("string"===typeof a?a:U(a),b);b=Yb(!!d,!!e);W.ra||(W.ra=64);var f=W.ra++<<8|0;mb(f,{open:function(a){a.seekable=!1},close:function(){e&&e.buffer&&e.buffer.length&&e(10)},read:function(a,b,e,f){for(var g=0,h=0;h<f;h++){try{var t=d()}catch(wa){throw new K(I.v);}if(void 0===t&&0===g)throw new K(I.ba);if(null===t||void 0===t)break;g++;b[e+h]=t}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,f){for(var g=0;g<f;g++)try{e(b[d+g])}catch(v){throw new K(I.v);}f&&(a.node.timestamp=
Date.now());return g}});return Mb(a,b,f)}function cc(a,b,d){a=J("string"===typeof a?a:U(a),b);return Nb(d,a)}
function dc(a){if(a.Ga||a.Ha||a.link||a.b)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(c.read)try{a.b=ob(c.read(a.url)),a.g=a.b.length}catch(d){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||db(I.v);return b}
function ec(a,b,d,e,f){function g(){this.Y=!1;this.M=[]}g.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.qa(a/this.chunkSize|0)[b]}};g.prototype.Pa=function(a){this.qa=a};g.prototype.ja=function(){var a=new XMLHttpRequest;a.open("HEAD",d,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+d+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),e,f=(e=a.getResponseHeader("Accept-Ranges"))&&"bytes"===
e;a=(e=a.getResponseHeader("Content-Encoding"))&&"gzip"===e;var g=1048576;f||(g=b);var h=this;h.Pa(function(a){var e=a*g,f=(a+1)*g-1;f=Math.min(f,b-1);if("undefined"===typeof h.M[a]){var t=h.M;if(e>f)throw Error("invalid range ("+e+", "+f+") or no bytes requested!");if(f>b-1)throw Error("only "+b+" bytes available! programmer error!");var v=new XMLHttpRequest;v.open("GET",d,!1);b!==g&&v.setRequestHeader("Range","bytes="+e+"-"+f);"undefined"!=typeof Uint8Array&&(v.responseType="arraybuffer");v.overrideMimeType&&
v.overrideMimeType("text/plain; charset=x-user-defined");v.send(null);if(!(200<=v.status&&300>v.status||304===v.status))throw Error("Couldn't load "+d+". Status: "+v.status);e=void 0!==v.response?new Uint8Array(v.response||[]):ob(v.responseText||"");t[a]=e}if("undefined"===typeof h.M[a])throw Error("doXHR failed!");return h.M[a]});if(a||!b)g=b=1,g=b=this.qa(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.za=b;this.ya=g;this.Y=!0};if("undefined"!==
typeof XMLHttpRequest){if(!n)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.Y||this.ja();return this.za}},chunkSize:{get:function(){this.Y||this.ja();return this.ya}}});var t=void 0}else t=d,h=void 0;var w=ac(a,b,e,f);h?w.b=h:t&&(w.b=null,w.url=t);Object.defineProperties(w,{g:{get:function(){return this.b.length}}});var M={};Object.keys(w.f).forEach(function(a){var b=
w.f[a];M[a]=function(){if(!dc(w))throw new K(I.v);return b.apply(null,arguments)}});M.read=function(a,b,d,e,f){if(!dc(w))throw new K(I.v);a=a.node.b;if(f>=a.length)return 0;e=Math.min(a.length-f,e);assert(0<=e);if(a.slice)for(var g=0;g<e;g++)b[d+g]=a[f+g];else for(g=0;g<e;g++)b[d+g]=a.get(f+g);return e};w.f=M;return w}
function fc(a,b,d,e,f,g,h,t,w,M){function v(d){function v(d){M&&M();t||bc(a,b,d,e,f,w);g&&g();Sa(wa)}var fa=!1;c.preloadPlugins.forEach(function(a){!fa&&a.canHandle(Va)&&(a.handle(d,Va,v,function(){h&&h();Sa(wa)}),fa=!0)});fa||v(d)}Browser.Xc();var Va=b?jb(J(a,b)):a,wa=Qa("cp "+Va);Ra(wa);"string"==typeof d?Browser.Sc(d,function(a){v(a)},h):v(d)}var FS={},Db,Jb,Rb,X=0;function Y(){X+=4;return z[X-4>>2]}function hc(){var a=Q[Y()];if(!a)throw new K(I.P);return a}Wb();R=Array(4096);Kb(L,"/");V("/tmp");
V("/home");V("/home/web_user");(function(){V("/dev");mb(259,{read:function(){return 0},write:function(a,b,f,g){return g}});Mb("/dev/null",259);lb(1280,pb);lb(1536,qb);Mb("/dev/tty",1280);Mb("/dev/tty1",1536);if("undefined"!==typeof crypto){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else b=p?function(){return require("crypto").randomBytes(1)[0]}:function(){return 256*Math.random()|0};W("/dev","random",b);W("/dev","urandom",b);V("/dev/shm");V("/dev/shm/tmp")})();
V("/proc");V("/proc/self");V("/proc/self/fd");Kb({i:function(){var a=sb("/proc/self","fd",16895,73);a.c={lookup:function(a,d){var b=Q[+d];if(!b)throw new K(I.P);a={parent:null,i:{ta:"fake"},c:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
Ka.unshift(function(){if(!c.noFSInit&&!Xb){assert(!Xb,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");Xb=!0;Wb();c.stdin=c.stdin;c.stdout=c.stdout;c.stderr=c.stderr;c.stdin?W("/dev","stdin",c.stdin):Nb("/dev/tty","/dev/stdin");c.stdout?W("/dev","stdout",null,c.stdout):Nb("/dev/tty","/dev/stdout");c.stderr?W("/dev","stderr",null,c.stderr):Nb("/dev/tty1","/dev/stderr");var a=
Qb("/dev/stdin","r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=Qb("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=Qb("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});La.push(function(){yb=!1});Ma.push(function(){Xb=!1;var a=c._fflush;a&&a(0);for(a=0;a<Q.length;a++){var b=Q[a];b&&Sb(b)}});c.FS_createFolder=Zb;c.FS_createPath=$b;c.FS_createDataFile=bc;c.FS_createPreloadedFile=fc;c.FS_createLazyFile=ec;c.FS_createLink=cc;
c.FS_createDevice=W;c.FS_unlink=Ob;Ka.unshift(function(){});Ma.push(function(){});if(p){var fs=require("fs"),ub=require("path");P.Ra()}C=ja(4);Ca=Da=la(u);B=Ca+Ha;Ea=la(B);z[C>>2]=Ea;ka=!0;assert(Ea<y,"TOTAL_MEMORY not big enough for stack");
function ob(a){for(var b=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++d)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:2097151>=e?b+4:67108863>=e?b+5:b+6}b=Array(b+1);a=qa(a,b,0,b.length);b.length=a;return b}c.wasmTableSize=43;c.wasmMaxTableSize=43;c.Ba={};
c.Ca={enlargeMemory:function(){Ga()},getTotalMemory:function(){return y},abortOnCannotGrowMemory:Ga,abortStackOverflow:function(a){r("Stack overflow! Attempted to allocate "+a+" bytes on the stack, but stack has only "+(B-da()+a)+" bytes available!")},nullFunc_ii:function(a){c.printErr("Invalid function pointer called with signature 'ii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");
c.printErr("Build with ASSERTIONS=2 for more info.");r(a)},nullFunc_iii:function(a){c.printErr("Invalid function pointer called with signature 'iii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");c.printErr("Build with ASSERTIONS=2 for more info.");
r(a)},nullFunc_iiii:function(a){c.printErr("Invalid function pointer called with signature 'iiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");c.printErr("Build with ASSERTIONS=2 for more info.");r(a)},nullFunc_v:function(a){c.printErr("Invalid function pointer called with signature 'v'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");
c.printErr("Build with ASSERTIONS=2 for more info.");r(a)},nullFunc_vi:function(a){c.printErr("Invalid function pointer called with signature 'vi'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");c.printErr("Build with ASSERTIONS=2 for more info.");
r(a)},nullFunc_viiii:function(a){c.printErr("Invalid function pointer called with signature 'viiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");c.printErr("Build with ASSERTIONS=2 for more info.");r(a)},nullFunc_viiiii:function(a){c.printErr("Invalid function pointer called with signature 'viiiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");
c.printErr("Build with ASSERTIONS=2 for more info.");r(a)},nullFunc_viiiiii:function(a){c.printErr("Invalid function pointer called with signature 'viiiiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)");c.printErr("Build with ASSERTIONS=2 for more info.");
r(a)},invoke_iii:function(a,b,d){try{return c.dynCall_iii(a,b,d)}catch(e){if("number"!==typeof e&&"longjmp"!==e)throw e;c.setThrew(1,0)}},invoke_vi:function(a,b){try{c.dynCall_vi(a,b)}catch(d){if("number"!==typeof d&&"longjmp"!==d)throw d;c.setThrew(1,0)}},___cxa_allocate_exception:function(a){return bb(a)},___cxa_find_matching_catch_2:function(){return $a.apply(null,arguments)},___cxa_free_exception:___cxa_free_exception,___cxa_throw:function(a,b,d){Za[a]={Na:a,Aa:a,type:b,Uc:d,Yc:0,Tc:!1,Zc:!1};
Ya=a;"uncaught_exception"in Xa?Xa.W++:Xa.W=1;throw a;},___lock:function(){},___resumeException:function(a){Ya||(Ya=a);throw a;},___setErrNo:db,___syscall140:function(a,b){X=b;try{var d=hc();Y();var e=Y(),f=Y(),g=Y();Ub(d,e,g);z[f>>2]=d.position;d.X&&0===e&&0===g&&(d.X=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof K||r(h),-h.D}},___syscall146:function(a,b){X=b;try{var d=hc(),e=Y();a:{var f=Y();for(b=a=0;b<f;b++){var g=Vb(d,pa,z[e+8*b>>2],z[e+(8*b+4)>>2],void 0);if(0>g){var h=
-1;break a}a+=g}h=a}return h}catch(t){return"undefined"!==typeof FS&&t instanceof K||r(t),-t.D}},___syscall54:function(a,b){X=b;try{var d=hc(),e=Y();switch(e){case 21509:case 21505:return d.tty?0:-I.B;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-I.B;case 21519:if(!d.tty)return-I.B;var f=Y();return z[f>>2]=0;case 21520:return d.tty?-I.l:-I.B;case 21531:a=f=Y();if(!d.f.Fa)throw new K(I.B);return d.f.Fa(d,e,a);case 21523:return d.tty?0:-I.B;default:r("bad ioctl syscall "+
e)}}catch(g){return"undefined"!==typeof FS&&g instanceof K||r(g),-g.D}},___syscall6:function(a,b){X=b;try{var d=hc();Sb(d);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof K||r(e),-e.D}},___unlock:function(){},_emscripten_memcpy_big:function(a,b,d){x.set(x.subarray(b,b+d),a);return a},_llvm_exp2_f32:function(a){return Math.pow(2,a)},DYNAMICTOP_PTR:C,STACKTOP:Da,STACK_MAX:B};var Z=c.asm(c.Ba,c.Ca,buffer),ic=Z.___errno_location;
Z.___errno_location=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return ic.apply(null,arguments)};var jc=Z._emu_compute_audio_samples;
Z._emu_compute_audio_samples=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return jc.apply(null,arguments)};var kc=Z._emu_get_audio_buffer;
Z._emu_get_audio_buffer=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return kc.apply(null,arguments)};var lc=Z._emu_get_audio_buffer_length;
Z._emu_get_audio_buffer_length=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return lc.apply(null,arguments)};var mc=Z._emu_get_current_position;
Z._emu_get_current_position=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return mc.apply(null,arguments)};var nc=Z._emu_get_max_position;
Z._emu_get_max_position=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return nc.apply(null,arguments)};var oc=Z._emu_get_sample_rate;
Z._emu_get_sample_rate=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return oc.apply(null,arguments)};var pc=Z._emu_get_track_info;
Z._emu_get_track_info=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return pc.apply(null,arguments)};var qc=Z._emu_load_file;
Z._emu_load_file=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return qc.apply(null,arguments)};var rc=Z._emu_seek_position;
Z._emu_seek_position=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return rc.apply(null,arguments)};var sc=Z._emu_set_subsong;
Z._emu_set_subsong=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return sc.apply(null,arguments)};var tc=Z._emu_teardown;
Z._emu_teardown=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return tc.apply(null,arguments)};var uc=Z._fflush;Z._fflush=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return uc.apply(null,arguments)};
var vc=Z._free;Z._free=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return vc.apply(null,arguments)};var wc=Z._llvm_bswap_i32;
Z._llvm_bswap_i32=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return wc.apply(null,arguments)};var xc=Z._malloc;Z._malloc=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return xc.apply(null,arguments)};
var yc=Z._memmove;Z._memmove=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return yc.apply(null,arguments)};var zc=Z._roundf;
Z._roundf=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return zc.apply(null,arguments)};var Ac=Z._sbrk;Z._sbrk=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Ac.apply(null,arguments)};
var Bc=Z.establishStackSpace;Z.establishStackSpace=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Bc.apply(null,arguments)};var Cc=Z.getTempRet0;
Z.getTempRet0=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Cc.apply(null,arguments)};var Dc=Z.setTempRet0;Z.setTempRet0=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Dc.apply(null,arguments)};
var Ec=Z.setThrew;Z.setThrew=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Ec.apply(null,arguments)};var Fc=Z.stackAlloc;
Z.stackAlloc=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Fc.apply(null,arguments)};var Gc=Z.stackRestore;Z.stackRestore=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Gc.apply(null,arguments)};
var Hc=Z.stackSave;Z.stackSave=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return Hc.apply(null,arguments)};c.asm=Z;
c.___errno_location=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.___errno_location.apply(null,arguments)};
c._emu_compute_audio_samples=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._emu_compute_audio_samples.apply(null,arguments)};
c._emu_get_audio_buffer=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._emu_get_audio_buffer.apply(null,arguments)};
c._emu_get_audio_buffer_length=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._emu_get_audio_buffer_length.apply(null,arguments)};
c._emu_get_current_position=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._emu_get_current_position.apply(null,arguments)};
c._emu_get_max_position=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._emu_get_max_position.apply(null,arguments)};
c._emu_get_sample_rate=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._emu_get_sample_rate.apply(null,arguments)};
c._emu_get_track_info=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._emu_get_track_info.apply(null,arguments)};
c._emu_load_file=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._emu_load_file.apply(null,arguments)};
c._emu_seek_position=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._emu_seek_position.apply(null,arguments)};
c._emu_set_subsong=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._emu_set_subsong.apply(null,arguments)};
c._emu_teardown=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._emu_teardown.apply(null,arguments)};
c._fflush=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._fflush.apply(null,arguments)};var Wa=c._free=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._free.apply(null,arguments)};
c._llvm_bswap_i32=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._llvm_bswap_i32.apply(null,arguments)};
var bb=c._malloc=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._malloc.apply(null,arguments)};
c._memmove=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._memmove.apply(null,arguments)};c._roundf=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._roundf.apply(null,arguments)};
c._sbrk=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm._sbrk.apply(null,arguments)};
c.establishStackSpace=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.establishStackSpace.apply(null,arguments)};
c.getTempRet0=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.getTempRet0.apply(null,arguments)};
var ia=c.setTempRet0=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.setTempRet0.apply(null,arguments)};
c.setThrew=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.setThrew.apply(null,arguments)};
var ha=c.stackAlloc=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.stackAlloc.apply(null,arguments)},ea=c.stackRestore=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.stackRestore.apply(null,
arguments)},da=c.stackSave=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.stackSave.apply(null,arguments)};
c.dynCall_iii=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.dynCall_iii.apply(null,arguments)};
c.dynCall_v=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.dynCall_v.apply(null,arguments)};
c.dynCall_vi=function(){assert(D,"you need to wait for the runtime to be ready (e.g. wait for main() to be called)");assert(!E,"the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)");return c.asm.dynCall_vi.apply(null,arguments)};c.asm=Z;c.intArrayFromString||(c.intArrayFromString=function(){r("'intArrayFromString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.intArrayToString||(c.intArrayToString=function(){r("'intArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.ccall=function(a,b,d,e){var f=c["_"+a];assert(f,"Cannot call unknown function "+a+", make sure it is exported");var g=[];a=0;assert("array"!==b,'Return type should not be "array".');if(e)for(var h=0;h<e.length;h++){var t=sa[d[h]];t?(0===a&&(a=da()),g[h]=t(e[h])):g[h]=e[h]}d=f.apply(null,g);"string"===b&&(d=ta(d));0!==a&&ea(a);return d};c.cwrap||(c.cwrap=function(){r("'cwrap' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.setValue||(c.setValue=function(){r("'setValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.getValue||(c.getValue=function(){r("'getValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.allocate||(c.allocate=function(){r("'allocate' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.getMemory=function(a){if(ka)if(D)var b=bb(a);else{assert(C);b=z[C>>2];a=b+a+15&-16;z[C>>2]=a;if(a=a>=y)Ga(),a=!0;a&&(z[C>>2]=b,b=0)}else b=ja(a);return b};c.Pointer_stringify=ta;c.AsciiToString||(c.AsciiToString=function(){r("'AsciiToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.stringToAscii||(c.stringToAscii=function(){r("'stringToAscii' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.UTF8ArrayToString||(c.UTF8ArrayToString=function(){r("'UTF8ArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.UTF8ToString||(c.UTF8ToString=function(){r("'UTF8ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.stringToUTF8Array||(c.stringToUTF8Array=function(){r("'stringToUTF8Array' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.stringToUTF8||(c.stringToUTF8=function(){r("'stringToUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.UTF16ToString||(c.UTF16ToString=function(){r("'UTF16ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.stringToUTF16||(c.stringToUTF16=function(){r("'stringToUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.lengthBytesUTF16||(c.lengthBytesUTF16=function(){r("'lengthBytesUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.UTF32ToString||(c.UTF32ToString=function(){r("'UTF32ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.stringToUTF32||(c.stringToUTF32=function(){r("'stringToUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.lengthBytesUTF32||(c.lengthBytesUTF32=function(){r("'lengthBytesUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.allocateUTF8||(c.allocateUTF8=function(){r("'allocateUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.stackTrace||(c.stackTrace=function(){r("'stackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.addOnPreRun||(c.addOnPreRun=function(){r("'addOnPreRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.addOnInit||(c.addOnInit=function(){r("'addOnInit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.addOnPreMain||(c.addOnPreMain=function(){r("'addOnPreMain' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.addOnExit||(c.addOnExit=function(){r("'addOnExit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.addOnPostRun||(c.addOnPostRun=function(){r("'addOnPostRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.writeStringToMemory||(c.writeStringToMemory=function(){r("'writeStringToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.writeArrayToMemory||(c.writeArrayToMemory=function(){r("'writeArrayToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.writeAsciiToMemory||(c.writeAsciiToMemory=function(){r("'writeAsciiToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.addRunDependency=Ra;c.removeRunDependency=Sa;c.FS||(c.FS=function(){r("'FS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.FS_createFolder=Zb;c.FS_createPath=$b;c.FS_createDataFile=bc;c.FS_createPreloadedFile=fc;c.FS_createLazyFile=ec;c.FS_createLink=cc;c.FS_createDevice=W;c.FS_unlink=Ob;c.GL||(c.GL=function(){r("'GL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.staticAlloc||(c.staticAlloc=function(){r("'staticAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.dynamicAlloc||(c.dynamicAlloc=function(){r("'dynamicAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.warnOnce||(c.warnOnce=function(){r("'warnOnce' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.loadDynamicLibrary||(c.loadDynamicLibrary=function(){r("'loadDynamicLibrary' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.loadWebAssemblyModule||(c.loadWebAssemblyModule=function(){r("'loadWebAssemblyModule' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.getLEB||(c.getLEB=function(){r("'getLEB' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.getFunctionTables||(c.getFunctionTables=function(){r("'getFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.alignFunctionTables||(c.alignFunctionTables=function(){r("'alignFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.registerFunctions||(c.registerFunctions=function(){r("'registerFunctions' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.addFunction||(c.addFunction=function(){r("'addFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.removeFunction||(c.removeFunction=function(){r("'removeFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.getFuncWrapper||(c.getFuncWrapper=function(){r("'getFuncWrapper' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.prettyPrint||(c.prettyPrint=function(){r("'prettyPrint' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.makeBigInt||(c.makeBigInt=function(){r("'makeBigInt' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.dynCall||(c.dynCall=function(){r("'dynCall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});c.getCompilerSetting||(c.getCompilerSetting=function(){r("'getCompilerSetting' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
c.ALLOC_NORMAL||Object.defineProperty(c,"ALLOC_NORMAL",{get:function(){r("'ALLOC_NORMAL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});c.ALLOC_STACK||Object.defineProperty(c,"ALLOC_STACK",{get:function(){r("'ALLOC_STACK' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});c.ALLOC_STATIC||Object.defineProperty(c,"ALLOC_STATIC",{get:function(){r("'ALLOC_STATIC' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});
c.ALLOC_DYNAMIC||Object.defineProperty(c,"ALLOC_DYNAMIC",{get:function(){r("'ALLOC_DYNAMIC' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});c.ALLOC_NONE||Object.defineProperty(c,"ALLOC_NONE",{get:function(){r("'ALLOC_NONE' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});function q(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}q.prototype=Error();q.prototype.constructor=q;var Ic=null;
Pa=function Jc(){c.calledRun||Kc();c.calledRun||(Pa=Jc)};
function Kc(){function a(){if(!c.calledRun&&(c.calledRun=!0,!oa)){Fa();D||(D=!0,Ia(Ka));Fa();Ia(La);m&&null!==Ic&&c.printErr("pre-main prep time: "+(Date.now()-Ic)+" ms");if(c.onRuntimeInitialized)c.onRuntimeInitialized();assert(!c._main,'compiled without a main, but one is present. if you added it from JS, use Module["onRuntimeInitialized"]');Fa();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var a=c.postRun.shift();Na.unshift(a)}Ia(Na)}}null===Ic&&(Ic=
Date.now());if(!(0<F)){assert(0==(B&3));A[(B>>2)-1]=34821223;A[(B>>2)-2]=2310721022;if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)Oa();Ia(Ja);0<F||c.calledRun||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},1);a()},1)):a(),Fa())}}c.run=Kc;
function Lc(){var a=c.print,b=c.printErr,d=!1;c.print=c.printErr=function(){d=!0};try{var e=c._fflush;e&&e(0);["stdout","stderr"].forEach(function(a){a="/dev/"+a;try{var b=T(a,{H:!0});a=b.path}catch(t){}var e={Ia:!1,exists:!1,error:0,name:null,path:null,object:null,Ka:!1,Ma:null,La:null};try{b=T(a,{parent:!0}),e.Ka=!0,e.Ma=b.path,e.La=b.node,e.name=hb(a),b=T(a,{H:!0}),e.exists=!0,e.path=b.path,e.object=b.node,e.name=b.node.name,e.Ia="/"===b.path}catch(t){e.error=t.D}e&&(b=kb[e.object.rdev])&&b.output&&
b.output.length&&(d=!0)})}catch(f){}c.print=a;c.printErr=b;d&&ma("stdio streams had content in them that was not flushed. you should set NO_EXIT_RUNTIME to 0 (see the FAQ), or make sure to emit a newline when you printf etc.")}
c.exit=function(a,b){Lc();if(!b||!c.noExitRuntime||0!==a){if(c.noExitRuntime)b||c.printErr("exit("+a+") called, but NO_EXIT_RUNTIME is set, so halting execution but not exiting the runtime or preventing further async execution (build with NO_EXIT_RUNTIME=0, if you want a true shutdown)");else if(oa=!0,Da=void 0,Fa(),Ia(Ma),E=!0,c.onExit)c.onExit(a);p&&process.exit(a);c.quit(a,new q(a))}};var Mc=[];
function r(a){if(c.onAbort)c.onAbort(a);void 0!==a?(c.print(a),c.printErr(a),a=JSON.stringify(a)):a="";oa=!0;var b="abort("+a+") at "+ya()+"";Mc&&Mc.forEach(function(d){b=d(b,a)});throw b;}c.abort=r;if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();c.noExitRuntime=!0;Kc();
  return {
	Module: Module,  // expose original Module
  };
})(window.spp_backend_state_V2M);
/*
 v2m_adapter.js: Adapts "V2 by farbrausch" backend to generic WebAudio/ScriptProcessor player.
 
 version 1.0
 
 	Copyright (C) 2018 Juergen Wothke

 LICENSE
 
	The Artistic License 2.0 Copyright (c) 2000-2006, The Perl Foundation.
*/
V2MBackendAdapter = (function(){ var $this = function () {
		$this.base.call(this, backend_V2M.Module, 2);
		this._manualSetupComplete= true;
		this._undefined;
		this._currentPath;
		this._currentFile;
		
		if (!backend_V2M.Module.notReady) {
			// in sync scenario the "onRuntimeInitialized" has already fired before execution gets here,
			// i.e. it has to be called explicitly here (in async scenario "onRuntimeInitialized" will trigger
			// the call directly)
			this.doOnAdapterReady();
		}				
	}; 
	// sample buffer contains 2-byte integer sample data (i.e. 
	// must be rescaled) of 2 interleaved channels
	extend(EmsHEAP16BackendAdapter, $this, {
		doOnAdapterReady: function() {
			// called when runtime is ready (e.g. asynchronously when WASM is loaded)
			// if FS needed to be setup of would be done here..
		},
		getAudioBuffer: function() {
			var ptr=  this.Module.ccall('emu_get_audio_buffer', 'number');			
			// make it a this.Module.HEAP16 pointer
			return ptr >> 1;	// 2 x 16 bit samples			
		},
		getAudioBufferLength: function() {
			var len= this.Module.ccall('emu_get_audio_buffer_length', 'number');
			return len;
		},
		computeAudioSamples: function() {
			return this.Module.ccall('emu_compute_audio_samples', 'number');
		},
		getMaxPlaybackPosition: function() { 
			return this.Module.ccall('emu_get_max_position', 'number');
		},
		getPlaybackPosition: function() {
			return this.Module.ccall('emu_get_current_position', 'number');
		},
		seekPlaybackPosition: function(pos) {
			this.Module.ccall('emu_seek_position', 'number', ['number'], [pos]);
		},		
		getPathAndFilename: function(filename) {
			var sp = filename.split('/');
			var fn = sp[sp.length-1];					
			var path= filename.substring(0, filename.lastIndexOf("/"));	
			if (path.lenght) path= path+"/";
			
			return [path, fn];
		},
		mapBackendFilename: function (name) {
			// "name" comes from the C++ side 
			var input= this.Module.Pointer_stringify(name);
			return input;
		},
		registerFileData: function(pathFilenameArray, data) {
			return this.registerEmscriptenFileData(pathFilenameArray, data);
		},
		loadMusicData: function(sampleRate, path, filename, data, options) {
			var buf = this.Module._malloc(data.length);
			this.Module.HEAPU8.set(data, buf);
			var ret = this.Module.ccall('emu_load_file', 'number', ['string', 'number', 'number'], [filename, buf, data.length]);
			this.Module._free(buf);

			if (ret == 0) {
				this.playerSampleRate = this.Module.ccall('emu_get_sample_rate', 'number');
				this.resetSampleRate(sampleRate, this.playerSampleRate);
				this._currentPath= path;
				this._currentFile= filename;
			} else {
				this._currentPath= this._undefined;
				this._currentFile= this._undefined;
			}
			return ret;			
		},
		evalTrackOptions: function(options) {
			if (typeof options.timeout != 'undefined') {
				ScriptNodePlayer.getInstance().setPlaybackTimeout(options.timeout*1000);
			} else {
				ScriptNodePlayer.getInstance().setPlaybackTimeout(-1);	// reset last songs setting
			}
			var id= (options && options.track) ? options.track : -1;	// by default do not set track		
			var boostVolume= (options && options.boostVolume) ? options.boostVolume : 0;		
			return this.Module.ccall('emu_set_subsong', 'number', ['number', 'number'], [id, boostVolume]);
		},				
		teardown: function() {
			this.Module.ccall('emu_teardown', 'number');	// just in case
		},
		getSongInfoMeta: function() {
			return {title: String,
					track: String, 
					artist: String, 
					copyright: String, 
					};
		},
		
		updateSongInfo: function(filename, result) {
			var numAttr= 1;
			var ret = this.Module.ccall('emu_get_track_info', 'number');

			var array = this.Module.HEAP32.subarray(ret>>2, (ret>>2)+numAttr);
			result.title= this.Module.Pointer_stringify(array[0]);
		}
	});	return $this; })();